version: "3"
services:
  web:
    image: gregorianisch/stagnation:service_stack
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - overlay_network
networks:
  overlay_network: